name: RSCNet
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.4
  - pytorch=2.2.0
  - pip=24.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.17.0
  
  - pip:
      - pytorch-lightning==2.2.0.post0
      - wandb==0.16.3
